name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/uifabric/fabricpublic
          azure-pipeline-name: 'Fluent UI React - PR and CI'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
